In [1]:
from votes_allocation_commons import *
import pickle
import warnings
from IPython.display import display, HTML

In [2]:
PARTIES = ["HDZ", "SDP", "MOST", "DP", "MOŽEMO"]
var_predictions = {
    "HDZ": 34.4,
    "SDP": 24.83,
    "MOST": 7.64,
    "DP": 9.69,
    "MOŽEMO": 9.12,
    "IZLAZNOST": 60.87
}

# divide each value of var_predictions by 100
var_predictions = {k: v/100 for k, v in var_predictions.items()}
num_voters = 3645340

In [3]:
with open("/home/tin/Documents/ai-izbori/parlametrika/data/frka_dictionary.pkl", "rb") as f:
    fixed = pickle.load(f)

In [4]:
with open("/home/tin/Documents/ai-izbori/parlametrika/data/ij_dict.pickle", "rb") as f:
    data_izborne_jedinice = pickle.load(f)

In [5]:
ig_2020 = IzbornaGodina(2020, data_izborne_jedinice, fixed)
mandate_prediction = MandatePrediction(ig_2020, var_predictions, num_voters)

predictions = {}
for ij in range(1, 11):
    mandates = 11 if ij == 8 else 14
    dhondt_dict = mandate_prediction.get_mandate_allocation_for_izborna_jedinica(ij_id=ij, mandates=mandates)
    predictions[ij] = dhondt_dict

In [6]:
warnings.filterwarnings("ignore")
for ij in range(1, 11):
    print(f"Izborna jedinica {ij}:")
    df = mandate_prediction.visualize_mandate_allocation(votes_per_party=predictions[ij]["votes_per_party"], allocated_mandates=predictions[ij]["allocated_mandates"], list_winners_num_votes=predictions[ij]["list_winners_num_votes"])
    display(HTML(df.to_html()))
    print("\n\n")

print("Ukupno:")
total_per_party = {party: sum([predictions[ij]["allocated_mandates"].get(party, 0) for ij in range(1, 11)]) for party in PARTIES}
print(total_per_party)

Izborna jedinica 1:

Izborna jedinica 2:

Izborna jedinica 3:

Izborna jedinica 4:

Izborna jedinica 5:

Izborna jedinica 6:

Izborna jedinica 7:

Izborna jedinica 8:

Izborna jedinica 9:

Izborna jedinica 10:

Ukupno:
{'HDZ': 63, 'SDP': 43, 'MOST': 7, 'DP': 13, 'MOŽEMO': 11}